ARG ASTRBOT_BASE_IMAGE
FROM ${ASTRBOT_BASE_IMAGE}

COPY patches/response-preference-cas.patch /tmp/response-preference-cas.patch

RUN cd /AstrBot \
    && patch --batch --forward -p1 < /tmp/response-preference-cas.patch \
    && python -m py_compile \
        astrbot/core/db/__init__.py \
        astrbot/core/db/sqlite.py \
        astrbot/core/utils/plugin_kv_store.py \
        astrbot/core/utils/shared_preferences.py \
    && rm /tmp/response-preference-cas.patch
